use_frameworks!

platform :ios, '9.0'

target 'DynamicDataStructures_Example' do
  pod 'DynamicDataStructures', :path => '../'

  target 'DynamicDataStructures_Tests' do
    inherit! :search_paths

    
  end
end
